import 'package:animate_do/animate_do.dart';
import 'package:flutter/material.dart';
import 'package:iconsax/iconsax.dart';
import 'package:qr_flutter/qr_flutter.dart';
import 'package:ship_to_naija/core/apptheme.dart';
import 'package:ship_to_naija/core/sizeConfig.dart';
import 'package:ship_to_naija/custom/btn.dart';
import 'package:ship_to_naija/custom/page_layout.dart';

import '../../../custom/txt.dart';

class SecurityTabView extends StatefulWidget {
  const SecurityTabView({super.key});

  @override
  State<SecurityTabView> createState() => _SecurityTabViewState();
}

class _SecurityTabViewState extends State<SecurityTabView> {
  bool isSwitched = true;

  @override
  Widget build(BuildContext context) {
    return      FadeInRight(
      delay: const Duration(milliseconds: 20),
      child: PageLayout(
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Two Factor Authentication(2FA)',
              style:
                  TextStyle(fontWeight: FontWeight.w500, fontSize: MySize.size18),
            ),
            const SizedBox(height: 14),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text('Activate 2FA', style: AppTheme.detailHeaderStyle()),
                Transform.scale(
                  scale: 0.8,
                  child: Switch(
                    onChanged: (val) {
                      setState(() {
                        isSwitched = val;
                      });
                    },
                    value: isSwitched,
                    activeColor: AppTheme.primaryColor,
                    activeTrackColor: AppTheme.primaryColor.withOpacity(0.3),
                    inactiveThumbColor: AppTheme.grey,
                    inactiveTrackColor: Colors.white,
                  ),
                )
              ],
            ),
            const Text(
                '1. You will need an authenticator mobile app to complete this process, such as one of the following:'),
            Text(
              'Google Authenticator',
              style: AppTheme.detailHeaderStyle(),
            ),
            Text('Microsoft Authenticator', style: AppTheme.detailHeaderStyle()),
            Text('Duo Mobile', style: AppTheme.detailHeaderStyle()),
            const SizedBox(height: 14),
            Center(
              child:      FadeInUp(
                delay: const Duration(milliseconds: 20),
                child: QrImageView(
                  data:
                      'HGTUOJHLO234EJDHFGDHYUD-HGTUOJHLO234EJDHFGDHYUD-HGTUOJHLO234EJDHFGDHYUD-HGTUOJHLO234EJDHFGDHYUD-HGTUOJHLO234EJDHFGDHYUD',
                  version: QrVersions.auto,
                  size: 200.0,
                ),
              ),
            ),
            const SizedBox(height: 14),
            const Text('2. Scan the QR code with your authenticator app.'),
            const Text(
              'if you can\'t scan the code, you can enter the secret key into your authenticator app.',
              style: TextStyle(color: Colors.grey),
            ),
            const SizedBox(height: 8),
            const PageLayout(
              borderRadius: 5,
              backgroundColor: Colors.transparent,
              isBorder: true,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text(
                    'HGTUOJHLO23JDHFGDHYUD',
                    style: TextStyle(color: Colors.grey),
                  ),
                  Icon(Iconsax.copy)
                ],
              ),
            ),
            const SizedBox(height: 16),
            const Text(
              '3. After scanning the QR code above, enter the six digits generated by your authenticator',
              style: TextStyle(fontWeight: FontWeight.w700),
            ),
            const SizedBox(height: 8),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: List.generate(
                  4,
                  (index) => Padding(
                        padding:
                            EdgeInsets.symmetric(horizontal: index == 0 ? 0 : 8),
                        child: const SizedBox(width: 50, child: Txt()),
                      )),
            ),
            const SizedBox(height: 16),
            RichText(
                text: const TextSpan(
                    text: '4. ',
                    children: [
                      TextSpan(
                        text: '**Note** ',
                        style: TextStyle(fontWeight: FontWeight.w700),
                      ),
                      TextSpan(
                          text:
                              'Make sure to store backup codes in a secure place in case you loose access to your primary authentication method.'),
                      TextSpan(text: ' Click here to reveal the backup codes.')
                    ],
                    style: TextStyle(color: Colors.black))),
            const SizedBox(height: 20),
            Row(
              children: [
                Expanded(
                  child: Btn(
                    enabledColor: Colors.transparent,
                    borderColor: AppTheme.primaryColor,
                    fontColor: AppTheme.primaryColor,
                    text: 'Cancel',
                    onPressed: () {},
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Btn(
                    enabledColor: AppTheme.primaryColor,
                    text: 'Verify',
                    onPressed: () {},
                  ),
                )
              ],
            )
          ],
        ),
      ),
    );
  }
}
